### PR TITLE
Re-merge frozen-phone branch

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**

### CODE REVIEW

**Comment by suhlrich** [comment]
closing to merge dev into it

**Comment by suhlrich** [comment]
I think this PR will be superceded by https://github.com/stanfordnmbl/opencap-api/pull/102. We can ignore these changes, I think. Let me know if you think otherwise, @AlbertoCasasOrtiz

**Review by suhlrich — COMMENTED** [review]
This looks good. Is this still relevant with how you're implementing https://github.com/stanfordnmbl/opencap-viewer/issues/79? Seems like the current implementation there is all on the frontend, which is kind of nice.

The changes in this PR related to internationalization remain relevent though.

**Comment by AlbertoCasasOrtiz** [comment]
I think everything from this PR is addressed in the number of phones issue, so we could close it.

Regarding intarnationalization, everything should be integrated in its own PR, including what it is here.

**Pull request closed without merging**
