### PR TITLE
WIP - Detecting frozen/disconnected/missing phones

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
- [x] Need to do search of root session recursive.
- [x] Need to figure out what happens if original session (with calib. trial) is removed (Created #45)

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
This needs to be tested in a real setup with phones. We can simulate a phone being frozen by turning network off.

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz is this ready to be merged in dev for testing?

**Comment by AlbertoCasasOrtiz** [comment]
Yes, it should be ready

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz I am bit confused, it this related to this? https://github.com/stanfordnmbl/opencap-viewer/issues/79
Or is it for now just going to display an error message if the number of videos is not the same as number of calibration videos?

**Pull request merged**
